from tkinter import *
def cal():
    inv=float(entry1.get())
    yr=int(entry2.get())
    ar=float(entry3.get())
    FV=inv*(1+(ar/12))*12*yr
    var.set(str(FV))
root=Tk()
L1 = Label(root, text="Investment amount")
L1.pack()    
entry1 = Entry(root)
entry1.pack()
L2 = Label(root, text="years")
L2.pack()    
entry2 = Entry(root)
entry2.pack()
L3 = Label(root, text="Annual interest rate")
L3.pack()    
entry3 = Entry(root)
entry3.pack()
L4 = Label(root, text="Future value")
L4.pack()    
var=StringVar()
L5 = Label(root, textvariable=var)
L5.pack()  
B1 = Button(root, text = "calculate", command = cal)
B1.pack()
root.mainloop()